/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-20 19:20:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Addmin_005fhomepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    // Get the username parameter from the request
    String username = request.getParameter("username");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background: #1A1E23 url('images/hom20.jpg') no-repeat center center fixed;\r\n");
      out.write("       \r\n");
      out.write("            background-size: cover; /* Adjust background size here */\r\n");
      out.write("            font-family: 'Lato', sans-serif;\r\n");
      out.write("            -webkit-font-smoothing: antialiased;\r\n");
      out.write("            padding-top: 20px; /* Add padding to push down the content */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav .line {\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            margin: 10px 0 0 0;\r\n");
      out.write("            background: #FF1847;\r\n");
      out.write("            transition: width 0.3s ease, left 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul {\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li {\r\n");
      out.write("            margin: 0 40px 0 0;\r\n");
      out.write("     \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("        nav ul li:last-child {\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("           \r\n");
      out.write("            display: block;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            letter-spacing: 0.1em;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Center */\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            animation: mymove 10s infinite;\r\n");
      out.write("            color: #F9F9F9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes mymove {\r\n");
      out.write("            from {left: 0px;}\r\n");
      out.write("            to {left: 920px;}\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li a:hover {\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("              color: aqua;\r\n");
      out.write("  box-shadow: rgb(251, 207, 250) 0px 100px 200px -1px;\r\n");
      out.write("  \r\n");
      out.write("        }\r\n");
      out.write("            h2 {\r\n");
      out.write("         \r\n");
      out.write("           text-decoration-color: red;\r\n");
      out.write("  \r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            color: #F9F9F9;\r\n");
      out.write("            top:50px;\r\n");
      out.write("       \r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("  .button {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 5%;\r\n");
      out.write("            left: 85%; /* Adjust as needed */\r\n");
      out.write("        }\r\n");
      out.write("   .butone{\r\n");
      out.write(" position: absolute;\r\n");
      out.write("    left: 97%;\r\n");
      out.write("    transform: translateX(-50%);\r\n");
      out.write("    top: 4%;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    padding: 5px 5px;\r\n");
      out.write("    border: 2px solid #333;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("@keyframes fadeIn {\r\n");
      out.write("    from {\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("    to {\r\n");
      out.write("        opacity: 40;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h2{\r\n");
      out.write("    animation: fadeIn 1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("<h2>Welcome: ");
      out.print( request.getParameter("username") );
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"LogoutServlet\" class=\"butone\">Logout</a>\r\n");
      out.write("<nav>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li class=\"active\"><a href=\"Addmin_AddOrder.jsp\">ORDER</a></li>\r\n");
      out.write("        <li><a href=\"payment.jsp\">PAYMENT</a></li>\r\n");
      out.write("        <li><a href=\"inventory.jsp\">INVENTORY</a></li>\r\n");
      out.write("        <li><a href=\"feedback.jsp\">FEEDBACK</a></li>\r\n");
      out.write("        ");
 if(session.getAttribute("username") == null){ 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <li><a href=\"viewepro\">USER</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"line\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
