/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-20 19:19:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Addmin_005fAddOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<script >\r\n");
      out.write(" function openNewJSP() {\r\n");
      out.write("    window.location.href = 'View'; \r\n");
      out.write("}\r\n");
      out.write(" function openNewJSP2() {\r\n");
      out.write("	    window.location.href = 'View'; \r\n");
      out.write("	}\r\n");
      out.write(" </script>\r\n");
      out.write("    \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Multi-Step Form with Table</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("  body {\r\n");
      out.write("   \r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("      background: url('images/14.jpg') no-repeat center center fixed;\r\n");
      out.write("      background-size: 100%; \r\n");
      out.write("             \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  .form-container {\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 5); \r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    animation: fadeIn 1s ease-in-out; /* Add fade-in animation */\r\n");
      out.write("   width: 500px;\r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 5); /* Adjust the alpha value (0.8) for transparency */\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  }\r\n");
      out.write("  form-container2{\r\n");
      out.write("   background-color: black;\r\n");
      out.write("  }\r\n");
      out.write("  /* Styles for form steps */\r\n");
      out.write("  .step {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .step.active {\r\n");
      out.write("    display: block;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  /* Styles for form inputs */\r\n");
      out.write("  input[type=\"text\"],\r\n");
      out.write("  input[type=\"date\"],\r\n");
      out.write("  select,\r\n");
      out.write("  input[type=\"number\"] {\r\n");
      out.write("    width: calc(100% - 20px);\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    margin: 10px 0;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  /* Styles for buttons */\r\n");
      out.write("  .button {\r\n");
      out.write("    background-color: rgb(90, 116, 139);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  }\r\n");
      out.write("  .homeBT11{\r\n");
      out.write("   background-color: rgb(90, 16, 139);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  }\r\n");
      out.write("  .ShowhomeBT{\r\n");
      out.write("    background-color: rgb(90, 116, 139);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  }\r\n");
      out.write("  .homeBT5{\r\n");
      out.write("    background-color: rgb(0, 0, 0);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("  .homeBT7{\r\n");
      out.write("    background-color: rgb(90, 116, 139);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 20px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  }\r\n");
      out.write("  .homeBT7{\r\n");
      out.write(" margin-bottom: 55px;\r\n");
      out.write("  }\r\n");
      out.write("  .homeBT8{\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: rgb(255, 173, 101);\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 20px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("  .homeBT9{\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color:rgb(48, 161, 116);\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 20px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 10px 5px 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("  .button:hover {\r\n");
      out.write("    background-color: rgb(94, 157, 211);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  /* Styles for result paragraph */\r\n");
      out.write("  #result {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("  }\r\n");
      out.write("  .form-container{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translateX(-50%);\r\n");
      out.write("     top: 25%;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("#clothType {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #clothType th, #clothType td {\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    border-bottom: 1px solid #ddd;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("     background-color: rgba(255, 255, 255, 5); \r\n");
      out.write("  }\r\n");
      out.write("      select#clothType1,#clothType2,#clothType3,#clothType4,#clothType5,#clothType6 {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: #306772;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    background-color: #f2f2f2;{\r\n");
      out.write("    color: #333;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .form-container{\r\n");
      out.write("   background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("  position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translateX(-50%);\r\n");
      out.write("     top: 25%;\r\n");
      out.write("     \r\n");
      out.write("  }\r\n");
      out.write("#step-6 {\r\n");
      out.write("  text-align: center; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("    font-size: 20px; \r\n");
      out.write("    font-weight: bold; \r\n");
      out.write("    color: #333; \r\n");
      out.write("    margin-bottom: 10px; \r\n");
      out.write("    display: block; \r\n");
      out.write("}\r\n");
      out.write(" #result {\r\n");
      out.write("            text-align: center; \r\n");
      out.write("            font-size: 50px; \r\n");
      out.write("        }\r\n");
      out.write(" .table-container {\r\n");
      out.write("     \r\n");
      out.write("    max-height: 300px;\r\n");
      out.write("    overflow-y: auto; \r\n");
      out.write("  }\r\n");
      out.write(".form-container {\r\n");
      out.write("   margin-bottom: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"multi-step-form\" method=\"post\" action=\"Addorder\" onsubmit=\"return showConfirmation()\"> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("      <div class=\"step active\" id=\"step-1\">\r\n");
      out.write("        <label for=\"CustomerID\">Customer_Name</label>\r\n");
      out.write("\r\n");
      out.write("        <input type=\"text\" id=\"CustomerID\" placeholder=\"Customer_Name\" name=\"CustomerID\" required>\r\n");
      out.write("       \r\n");
      out.write("        <button type=\"button\" class=\"button\" onclick=\"nextStep(1)\" >Next </button>\r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"step\" id=\"step-2\">\r\n");
      out.write("        <label for=\"OrderDate\">OrderDate</label>\r\n");
      out.write("        <input type=\"date\" id=\"OrderDate\" placeholder=\"Contact\" name=\"OrderDate\" required>\r\n");
      out.write("        <button type=\"button\" class=\"button\" onclick=\"nextStep(2)\">Next</button>\r\n");
      out.write("        <button type=\"button\" class=\"homeBT5\" onclick=\"prevStep(2)\">Previous</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("     <div class=\"mainstep\">\r\n");
      out.write("     <div class=\"step\" id=\"step-3\">\r\n");
      out.write("        <div class=\"table-container\">\r\n");
      out.write("          <table id=\"clothType\" class=\"anjutabe\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th>Cloth Type</th>\r\n");
      out.write("                <th>Quantity</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <select id=\"clothType1\" name=\"type1\">\r\n");
      out.write("                    <option value=\"No\">No</option>\r\n");
      out.write("                    <option value=\"Towels\">Towels</option>\r\n");
      out.write("                    <option value=\"Bedsheets\">Bedsheets</option>\r\n");
      out.write("                    <option value=\"Pillow cases\">Pillow cases</option>\r\n");
      out.write("                    <option value=\"Curtains\">Curtains</option>\r\n");
      out.write("                    <option value=\"Trouser\">Trouser</option>\r\n");
      out.write("                    <option value=\"Blouse\">Blouse</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"number\" class=\"quantity-input\" id=\"1-quantity\" name=\"inquantity1\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <select id=\"clothType2\" name=\"type2\">\r\n");
      out.write("                    <option value=\"No\">No</option>\r\n");
      out.write("                    <option value=\"Towels\">Towels</option>\r\n");
      out.write("                    <option value=\"Bedsheets\">Bedsheets</option>\r\n");
      out.write("                    <option value=\"Pillow cases\">Pillow cases</option>\r\n");
      out.write("                    <option value=\"Curtains\">Curtains</option>\r\n");
      out.write("                    <option value=\"Trouser\">Trouser</option>\r\n");
      out.write("                    <option value=\"Blouse\">Blouse</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"number\" class=\"quantity-input\" id=\"2-quantity\" name=\"inquantity2\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <select id=\"clothType3\" name=\"type3\">\r\n");
      out.write("                    <option value=\"No\">No</option>\r\n");
      out.write("                    <option value=\"Towels\">Towels</option>\r\n");
      out.write("                    <option value=\"Bedsheets\">Bedsheets</option>\r\n");
      out.write("                    <option value=\"Pillow cases\">Pillow cases</option>\r\n");
      out.write("                    <option value=\"Curtains\">Curtains</option>\r\n");
      out.write("                    <option value=\"Trouser\">Trouser</option>\r\n");
      out.write("                    <option value=\"Blouse\">Blouse</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"number\" class=\"quantity-input\" id=\"3-quantity\" name=\"inquantity3\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <select id=\"clothType4\" name=\"type4\">\r\n");
      out.write("                    <option value=\"No\">No</option>\r\n");
      out.write("                    <option value=\"Towels\">Towels</option>\r\n");
      out.write("                    <option value=\"Bedsheets\">Bedsheets</option>\r\n");
      out.write("                    <option value=\"Pillow cases\">Pillow cases</option>\r\n");
      out.write("                    <option value=\"Curtains\">Curtains</option>\r\n");
      out.write("                    <option value=\"Trouser\">Trouser</option>\r\n");
      out.write("                    <option value=\"Blouse\">Blouse</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"number\" class=\"quantity-input\" id=\"4-quantity\" name=\"inquantity4\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"clothType5\" name=\"type5\">\r\n");
      out.write("                        <option value=\"No\">No</option>\r\n");
      out.write("                        <option value=\"Towels\">Towels</option>\r\n");
      out.write("                        <option value=\"Bedsheets\">Bedsheets</option>\r\n");
      out.write("                        <option value=\"Pillow cases\">Pillow cases</option>\r\n");
      out.write("                        <option value=\"Curtains\">Curtains</option>\r\n");
      out.write("                        <option value=\"Trouser\">Trouser</option>\r\n");
      out.write("                        <option value=\"Blouse\">Blouse</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"number\" class=\"quantity-input\" id=\"5-quantity\" name=\"inquantity5\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"clothType6\" name=\"type6\">\r\n");
      out.write("                        <option value=\"No\">No</option>\r\n");
      out.write("                        <option value=\"Towels\">Towels</option>\r\n");
      out.write("                        <option value=\"Bedsheets\">Bedsheets</option>\r\n");
      out.write("                        <option value=\"Pillow cases\">Pillow cases</option>\r\n");
      out.write("                        <option value=\"Curtains\">Curtains</option>\r\n");
      out.write("                        <option value=\"Trouser\">Trouser</option>\r\n");
      out.write("                        <option value=\"Blouse\">Blouse</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"number\" class=\"quantity-input\" id=\"6-quantity\" name=\"inquantity6\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p id=\"quantity\"></p>\r\n");
      out.write(" <button type=\"button\" class=\"homeBT11\" onclick=\"quantity_calculateSum()\">Quantity</button>\r\n");
      out.write("    <button type=\"button\" class=\"button\" onclick=\"nextStep(3)\">Next</button>\r\n");
      out.write("       <button type=\"button\" class=\"homeBT5\" onclick=\"prevStep(3)\">Previous</button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Fourth Step -->\r\n");
      out.write("    <div class=\"step\" id=\"step-4\">\r\n");
      out.write("       \r\n");
      out.write("        <label for=\"clothType\">Enter Cloth Weight Type</label>\r\n");
      out.write("        <select id=\"optionValue\" name=\"clothType\">\r\n");
      out.write("            <option value=\"1\">Kilograms</option>\r\n");
      out.write("            <option value=\"2\">Grams</option>\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"button\" class=\"button\" onclick=\"nextStep(4)\" id=\"step-4-button\">Next</button>\r\n");
      out.write("         <button type=\"button\" class=\"homeBT5\" onclick=\"prevStep(4)\">Previous</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"step\" id=\"step-5\">\r\n");
      out.write("        <label for=\"weight\">Enter Weight</label>\r\n");
      out.write("        <input type=\"number\" id=\"weight\" placeholder=\"Enter Weight\" name=\"weight\" required>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"button\" class=\"button\" onclick=\"nextStep(5)\" id=\"step-5-button\">Next</button>\r\n");
      out.write("       <button type=\"button\" class=\"homeBT5\" onclick=\"prevStep(5)\">Previous</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- Fifth Step -->\r\n");
      out.write("<div class=\"step\" id=\"step-6\" >\r\n");
      out.write("  <p id=\"result\"></p>\r\n");
      out.write("  <button type=\"button\" class=\"homeBT7\" onclick=\"prevStep(6)\">Previous</button>\r\n");
      out.write(" \r\n");
      out.write("  <button type=\"button\" class=\"homeBT8\" onclick=\"calculateSum()\">Calculate</button>\r\n");
      out.write("       <input class=\"homeBT9\"  type=\"submit\" value=\"Submit\" name=\"oder-add\"  > \r\n");
      out.write(" <a class=\"homeBT7\" href=\"View\" target=\"_blank\" id=\"navigateUpdate\"  onclick=\"openNewJSP2()\">View Details</a>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function calculateSum() {\r\n");
      out.write("    var optionValue = parseInt(document.getElementById(\"optionValue\").value) || 0;;\r\n");
      out.write("    var weight = parseInt(document.getElementById(\"weight\").value) || 0;;\r\n");
      out.write("    var add;\r\n");
      out.write("\r\n");
      out.write("    if (optionValue === 1) {\r\n");
      out.write("        add = 200;\r\n");
      out.write("    } else if (optionValue === 2) {\r\n");
      out.write("        add = 20;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var sum = add * weight;\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"Total: \" + sum +\"Rs\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function quantity_calculateSum(){\r\n");
      out.write("    var quantity1 = parseInt(document.getElementById(\"1-quantity\").value) || 0; \r\n");
      out.write("    var quantity2 = parseInt(document.getElementById(\"2-quantity\").value) || 0; \r\n");
      out.write("    var quantity3 = parseInt(document.getElementById(\"3-quantity\").value) || 0; \r\n");
      out.write("    var quantity4 = parseInt(document.getElementById(\"4-quantity\").value) || 0; \r\n");
      out.write("    var quantity5 = parseInt(document.getElementById(\"5-quantity\").value) || 0; \r\n");
      out.write("    var quantity6 = parseInt(document.getElementById(\"6-quantity\").value) || 0;\r\n");
      out.write("\r\n");
      out.write("    var sum = quantity1 + quantity2 + quantity3+ quantity4+ quantity5+ quantity6;\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"quantity\").innerHTML = \"Total: \" + sum ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function nextStep(currentStep) {\r\n");
      out.write("    var isValid = true;\r\n");
      out.write("\r\n");
      out.write("    if (currentStep === 1) {\r\n");
      out.write("        var customerID = document.getElementById('CustomerID').value;\r\n");
      out.write("        if (customerID.trim() === '') {\r\n");
      out.write("            alert('Please Enter a Customer Name.');\r\n");
      out.write("            isValid = false;\r\n");
      out.write("        } else if (customerID.trim() === '0') { \r\n");
      out.write("            alert('Customer Name Cannot be 0.');\r\n");
      out.write("            isValid = false;\r\n");
      out.write("        }\r\n");
      out.write("        else if (customerID.trim() <= 0) { \r\n");
      out.write("            alert('Customer Name Cannot be -1.');\r\n");
      out.write("            isValid = false;\r\n");
      out.write("        }\r\n");
      out.write("    } else if (currentStep === 2) {\r\n");
      out.write("        var orderDate = document.getElementById('OrderDate').value;\r\n");
      out.write("        if (orderDate.trim() === '') {\r\n");
      out.write("            alert('Please select an Order Date.');\r\n");
      out.write("            isValid = false;\r\n");
      out.write("        }\r\n");
      out.write("    } else if (currentStep === 3) {\r\n");
      out.write("    	\r\n");
      out.write("    } else if (currentStep === 5) {\r\n");
      out.write("        var weight = document.getElementById('weight').value;\r\n");
      out.write("        if (weight.trim() === '') {\r\n");
      out.write("            alert('Please select weight.');\r\n");
      out.write("            isValid = false;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (isValid) {\r\n");
      out.write("        document.getElementById('step-' + currentStep).classList.remove('active');\r\n");
      out.write("        document.getElementById('step-' + (currentStep + 1)).classList.add('active');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function prevStep(currentStep) {\r\n");
      out.write("    document.getElementById('step-' + currentStep).classList.remove('active');\r\n");
      out.write("    document.getElementById('step-' + (currentStep - 1)).classList.add('active');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showConfirmation() {\r\n");
      out.write("    \r\n");
      out.write("    var confirmation = confirm(\" Add the order?\");\r\n");
      out.write("    if (confirmation) {\r\n");
      out.write("      \r\n");
      out.write("        alert(\"Order ADD!\");\r\n");
      out.write("     \r\n");
      out.write("    } else {\r\n");
      out.write("       \r\n");
      out.write("        alert(\"Order canceled.\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateWeight() {\r\n");
      out.write("    var weightInput = document.getElementById(\"weight\");\r\n");
      out.write("    var weight = parseFloat(weightInput.value);\r\n");
      out.write("\r\n");
      out.write("    if (isNaN(weight) || weight <= 0 || weight > 500) {\r\n");
      out.write("        \r\n");
      out.write("        alert(\"Maximum weight allowed is 500 kg.\");\r\n");
      out.write("        weightInput.value = \"\";\r\n");
      out.write("        weightInput.focus(); \r\n");
      out.write("        return false; \r\n");
      out.write("    } else {\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"weight\").addEventListener(\"input\", validateWeight);\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
