/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-21 04:19:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Add Payment</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("       \r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("          \r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background: url('images/777.jpg') no-repeat center center fixed;\r\n");
      out.write("      background-size: 100%; \r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        .closeMain {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .closeMain img {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        form {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("       \r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"text\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("            input[type=\"date\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("             background-color: rgb(7, 139, 97);\r\n");
      out.write("    color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         select#Cardholder_Name {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color:rgb(0, 35, 78);\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        input[type=\"submit\"]:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("        .a1 {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        div{\r\n");
      out.write("        top: 15%;\r\n");
      out.write("          position: absolute;\r\n");
      out.write("         left: 40%;\r\n");
      out.write("         transform: translateX(-50%);\r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .closeMain {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 2%;\r\n");
      out.write("            left: 2%;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .main-imd img{\r\n");
      out.write("        margin-left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #pay {\r\n");
      out.write("  background-color:  rgb(48, 75, 66);\r\n");
      out.write("  border: none; \r\n");
      out.write("  color: white; \r\n");
      out.write("  padding: 15px 15px; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  font-size: 16px; \r\n");
      out.write("  margin: 4px 2px; \r\n");
      out.write("  transition-duration: 0.4s; \r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("}\r\n");
      out.write(".a1 {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("      background-color: rgb(90, 116, 139);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a1:hover {\r\n");
      out.write("    background-color: #066a4a; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <img alt=\"\" src=\"images/pay.png\"width=\"400px\" height=\"400px\">\r\n");
      out.write("  <div class=\"main-imd\">\r\n");
      out.write("    <form action=\"AddPayment\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("    <label for=\"Card_number\">Card Number:</label>\r\n");
      out.write("    <input type=\"text\" id=\"Card_number\" name=\"Card_number\" maxlength=\"16\"required  placeholder=\"0123 0123 0123 0123\" pattern=\"\\d{16}\">\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"ExDate\">Expiration Date:</label>\r\n");
      out.write("    <input type=\"date\" id=\"ExDate\" name=\"ExDate\" required >\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"Cvv\">CVV:</label>\r\n");
      out.write("    <input type=\"text\" id=\"Cvv\" name=\"Cvv\" maxlength=\"3\" required placeholder=\"475\">\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"Cardholder_Name\">Cardholder Name:</label>\r\n");
      out.write("     <select id=\"Cardholder_Name\" name=\"Cardholder_Name\" required >\r\n");
      out.write("            <option value=\"\">Cardholder Name add</option>\r\n");
      out.write("            <option value=\"BOC\">BOC</option>\r\n");
      out.write("            <option value=\"HNB\">HNB</option>\r\n");
      out.write("             <option value=\"NDB\">NDB</option>\r\n");
      out.write("              <option value=\"SAMPATH\">SAMPATH</option>\r\n");
      out.write("                  <option value=\"DFCC\">DFCC</option>\r\n");
      out.write("                      <option value=\"COMMERCIAL\">COMMERCIAL</option>\r\n");
      out.write("           \r\n");
      out.write("          \r\n");
      out.write("          </select>\r\n");
      out.write("    <label for=\"Amount\">Amount:</label>\r\n");
      out.write("    <input type=\"text\" id=\"Amount\" name=\"Amount\" required>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"submit\" value=\"Add Card\">\r\n");
      out.write("   \r\n");
      out.write("   <a class=\"a1\" href=\"PaymentView\" target=\"_blank\"onclick=\"openNewJSP()\">Show</a>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        var cvv = document.getElementById(\"Cvv\").value;\r\n");
      out.write("        if (cvv.length > 3) {\r\n");
      out.write("            alert(\"CVV should be a maximum of three characters.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        var number = document.getElementById(\"Card_number\").value;\r\n");
      out.write("        if (number.length > 16) {\r\n");
      out.write("            alert(\"Card number should be a maximum of 16 characters.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("    function openNewJSP() {\r\n");
      out.write("        window.location.href = 'PaymentView'; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
