/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-21 04:40:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class UpdateOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Edit Order</title>\r\n");
      out.write("   <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("              background: url('images/add3.jpg') no-repeat center center fixed;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        form {\r\n");
      out.write("        \r\n");
      out.write("        background-color: rgba(255, 255, 255, 5); \r\n");
      out.write("              \r\n");
      out.write("            width: 900px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"number\"],\r\n");
      out.write("        input[type=\"date\"],\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"submit\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("              border: none; \r\n");
      out.write("  color: black; \r\n");
      out.write("  padding: 10px 10px; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  font-size: 16px; \r\n");
      out.write("  margin: 4px 2px; \r\n");
      out.write("  transition-duration: 0.4s; \r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        select{\r\n");
      out.write("           width: 100%;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"] {\r\n");
      out.write("            background-color: rgb(18, 19, 18);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"]:hover {\r\n");
      out.write("            background-color:rgba(33, 34, 34, 0.725);\r\n");
      out.write("        }\r\n");
      out.write("        .closeMain {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 2%;\r\n");
      out.write("            left: 0%;\r\n");
      out.write("        }\r\n");
      out.write("         table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        th, td {\r\n");
      out.write("         border: 1px solid #ddd; /* Add border to table cells */\r\n");
      out.write("      \r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        th {\r\n");
      out.write("         \r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("       #CustomerID {\r\n");
      out.write("  background-color:rgb(62, 94, 66);\r\n");
      out.write("  border: none; \r\n");
      out.write("  color: white; \r\n");
      out.write("  padding: 15px 15px; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  font-size: 16px; \r\n");
      out.write("  margin: 4px 2px; \r\n");
      out.write("  transition-duration: 0.4s; \r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("         #CustomerID {\r\n");
      out.write("  background-color:rgba(0, 192, 102, 0.725);\r\n");
      out.write("  border: none; \r\n");
      out.write("  color: white; \r\n");
      out.write("  padding: 15px 15px; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  font-size: 16px; \r\n");
      out.write("  margin: 4px 2px; \r\n");
      out.write("  transition-duration: 0.4s; \r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("  }\r\n");
      out.write("         #type1,  #type2,  #type3,  #type4,  #type5,  #type6{\r\n");
      out.write("  background-color: rgba(0, 108, 147, 0.725);\r\n");
      out.write("  border: none; \r\n");
      out.write("  color: white; \r\n");
      out.write("  padding: 11px 11px; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  font-size: 16px; \r\n");
      out.write("  margin: 4px 2px; \r\n");
      out.write("  transition-duration: 0.4s; \r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("  }\r\n");
      out.write("  div{\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("      #clothType {\r\n");
      out.write("          width: 100%;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("              border: none; \r\n");
      out.write("  color: black; \r\n");
      out.write("  padding: 10px 10px; \r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("  display: inline-block; \r\n");
      out.write("  font-size: 16px; \r\n");
      out.write("  margin: 4px 2px; \r\n");
      out.write("  transition-duration: 0.4s; \r\n");
      out.write("  cursor: pointer; \r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write(" <form action=\"UpdateOrder\" method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( request.getParameter("id") );
      out.write("\">\r\n");
      out.write("    <div>ID:");
      out.print( request.getParameter("id") );
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><label for=\"CustomerID\"> Customer_Name:</label></td>\r\n");
      out.write("            <td><input type=\"text\" id=\"CustomerID\" name=\"CustomerID\" value=\"");
      out.print( request.getParameter("CustomerID") );
      out.write("\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><label for=\"OrderDate\"> Order Date:</label></td>\r\n");
      out.write("            <td><input type=\"text\" id=\"OrderDate\" name=\"OrderDate\" value=\"");
      out.print( request.getParameter("OrderDate") );
      out.write("\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><label for=\"clothType\"> Enter Cloth Weight Type:</label></td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <select id=\"clothType\" name=\"clothType\">\r\n");
      out.write("                    <option value=\"Kilograms\" ");
      out.print( (request.getParameter("clothType") != null && request.getParameter("clothType").equals("Kilograms")) ? "selected" : "" );
      out.write(">Kilograms</option>\r\n");
      out.write("                    <option value=\"Grams\" ");
      out.print( (request.getParameter("clothType") != null && request.getParameter("clothType").equals("Grams")) ? "selected" : "" );
      out.write(">Grams</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("          <tr>\r\n");
      out.write("           <td>\r\n");
      out.write("<select id=\"type1\" name=\"type1\">\r\n");
      out.write("    <option value=\"No\" ");
      out.print( "No".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">No</option>\r\n");
      out.write("    <option value=\"Towels\" ");
      out.print( "Towels".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">Towels</option>\r\n");
      out.write("    <option value=\"Bedsheets\" ");
      out.print( "Bedsheets".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">Bedsheets</option>\r\n");
      out.write("    <option value=\"Pillow cases\" ");
      out.print( "Pillow cases".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">Pillow cases</option>\r\n");
      out.write("    <option value=\"Curtains\" ");
      out.print( "Curtains".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">Curtains</option>\r\n");
      out.write("    <option value=\"Trouser\" ");
      out.print( "Trouser".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">Trouser</option>\r\n");
      out.write("    <option value=\"Blouse\" ");
      out.print( "Blouse".equals(request.getParameter("type1")) ? "selected" : "" );
      out.write(">Blouse</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("                </td>\r\n");
      out.write("           <td><input type=\"text\" class=\"quantity-input\" id=\"1-quantity\" name=\"inquantity1\"value=\"");
      out.print( request.getParameter("inquantity1") );
      out.write("\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("                 <td>\r\n");
      out.write("        \r\n");
      out.write("   <select id=\"type2\" name=\"type2\">\r\n");
      out.write("    <option value=\"No\" ");
      out.print( "No".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">No</option>\r\n");
      out.write("    <option value=\"Towels\" ");
      out.print( "Towels".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">Towels</option>\r\n");
      out.write("    <option value=\"Bedsheets\" ");
      out.print( "Bedsheets".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">Bedsheets</option>\r\n");
      out.write("    <option value=\"Pillow cases\" ");
      out.print( "Pillow cases".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">Pillow cases</option>\r\n");
      out.write("    <option value=\"Curtains\" ");
      out.print( "Curtains".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">Curtains</option>\r\n");
      out.write("    <option value=\"Trouser\" ");
      out.print( "Trouser".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">Trouser</option>\r\n");
      out.write("    <option value=\"Blouse\" ");
      out.print( "Blouse".equals(request.getParameter("type2")) ? "selected" : "" );
      out.write(">Blouse</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"text\" class=\"quantity-input\" id=\"2-quantity\" name=\"inquantity2\" value=\"");
      out.print( request.getParameter("inquantity2") );
      out.write("\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("   <select id=\"type3\" name=\"type3\">\r\n");
      out.write("    <option value=\"No\" ");
      out.print( "No".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">No</option>\r\n");
      out.write("    <option value=\"Towels\" ");
      out.print( "Towels".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">Towels</option>\r\n");
      out.write("    <option value=\"Bedsheets\" ");
      out.print( "Bedsheets".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">Bedsheets</option>\r\n");
      out.write("    <option value=\"Pillow cases\" ");
      out.print( "Pillow cases".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">Pillow cases</option>\r\n");
      out.write("    <option value=\"Curtains\" ");
      out.print( "Curtains".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">Curtains</option>\r\n");
      out.write("    <option value=\"Trouser\" ");
      out.print( "Trouser".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">Trouser</option>\r\n");
      out.write("    <option value=\"Blouse\" ");
      out.print( "Blouse".equals(request.getParameter("type3")) ? "selected" : "" );
      out.write(">Blouse</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"text\" class=\"quantity-input\" id=\"3-quantity\" name=\"inquantity3\"value=\"");
      out.print( request.getParameter("inquantity3") );
      out.write("\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("        \r\n");
      out.write("   <select id=\"type4\" name=\"type4\">\r\n");
      out.write("    <option value=\"No\" ");
      out.print( "No".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">No</option>\r\n");
      out.write("    <option value=\"Towels\" ");
      out.print( "Towels".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">Towels</option>\r\n");
      out.write("    <option value=\"Bedsheets\" ");
      out.print( "Bedsheets".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">Bedsheets</option>\r\n");
      out.write("    <option value=\"Pillow cases\" ");
      out.print( "Pillow cases".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">Pillow cases</option>\r\n");
      out.write("    <option value=\"Curtains\" ");
      out.print( "Curtains".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">Curtains</option>\r\n");
      out.write("    <option value=\"Trouser\" ");
      out.print( "Trouser".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">Trouser</option>\r\n");
      out.write("    <option value=\"Blouse\" ");
      out.print( "Blouse".equals(request.getParameter("type4")) ? "selected" : "" );
      out.write(">Blouse</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"text\" class=\"quantity-input\" id=\"4-quantity\" name=\"inquantity4\"value=\"");
      out.print( request.getParameter("inquantity4") );
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                   <td>\r\n");
      out.write("        \r\n");
      out.write("   <select id=\"type5\" name=\"type5\">\r\n");
      out.write("    <option value=\"No\" ");
      out.print( "No".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">No</option>\r\n");
      out.write("    <option value=\"Towels\" ");
      out.print( "Towels".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">Towels</option>\r\n");
      out.write("    <option value=\"Bedsheets\" ");
      out.print( "Bedsheets".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">Bedsheets</option>\r\n");
      out.write("    <option value=\"Pillow cases\" ");
      out.print( "Pillow cases".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">Pillow cases</option>\r\n");
      out.write("    <option value=\"Curtains\" ");
      out.print( "Curtains".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">Curtains</option>\r\n");
      out.write("    <option value=\"Trouser\" ");
      out.print( "Trouser".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">Trouser</option>\r\n");
      out.write("    <option value=\"Blouse\" ");
      out.print( "Blouse".equals(request.getParameter("type5")) ? "selected" : "" );
      out.write(">Blouse</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"text\" class=\"quantity-input\" id=\"5-quantity\" name=\"inquantity5\"value=\"");
      out.print( request.getParameter("inquantity5") );
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("        \r\n");
      out.write("  <select id=\"type6\" name=\"type6\">\r\n");
      out.write("    <option value=\"No\" ");
      out.print( "No".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">No</option>\r\n");
      out.write("    <option value=\"Towels\" ");
      out.print( "Towels".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">Towels</option>\r\n");
      out.write("    <option value=\"Bedsheets\" ");
      out.print( "Bedsheets".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">Bedsheets</option>\r\n");
      out.write("    <option value=\"Pillow cases\" ");
      out.print( "Pillow cases".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">Pillow cases</option>\r\n");
      out.write("    <option value=\"Curtains\" ");
      out.print( "Curtains".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">Curtains</option>\r\n");
      out.write("    <option value=\"Trouser\" ");
      out.print( "Trouser".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">Trouser</option>\r\n");
      out.write("    <option value=\"Blouse\" ");
      out.print( "Blouse".equals(request.getParameter("type6")) ? "selected" : "" );
      out.write(">Blouse</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("                </td>\r\n");
      out.write("                <td><input type=\"text\" class=\"quantity-input\" id=\"6-quantity\" name=\"inquantity6\" value=\"");
      out.print( request.getParameter("inquantity6") );
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><label for=\"weight\">Enter Weight:</label></td>\r\n");
      out.write("            <td><input type=\"text\" id=\"weight\" name=\"weight\" value=\"");
      out.print( request.getParameter("weight") );
      out.write("\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      \r\n");
      out.write("       <tr>\r\n");
      out.write("            <td><label for=\"weight\">Price:</label></td>\r\n");
      out.write("            <td><input type=\"text\" id=\"price\" name=\"price\" value=\"");
      out.print( request.getParameter("price") );
      out.write("\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\"><input type=\"submit\" value=\"Update Order\"onclick=\"confirmUpdate()\"></td>\r\n");
      out.write("              \r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</form>\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("  <script>\r\n");
      out.write("        function confirmUpdate() {\r\n");
      out.write("           \r\n");
      out.write("            var confirmation = confirm(\"Are you sure you  update the order?\");\r\n");
      out.write("            if (confirmation) {\r\n");
      out.write("              \r\n");
      out.write("                alert(\"Order updated!\");\r\n");
      out.write("             \r\n");
      out.write("            } else {\r\n");
      out.write("               \r\n");
      out.write("                alert(\"Update canceled.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function confirmUpdate() {\r\n");
      out.write("            \r\n");
      out.write("            var confirmation = confirm(\"Are you sure you  update the order?\");\r\n");
      out.write("            if (confirmation) {\r\n");
      out.write("              \r\n");
      out.write("                alert(\"Order updated!\");\r\n");
      out.write("             \r\n");
      out.write("            } else {\r\n");
      out.write("               \r\n");
      out.write("                alert(\"Update canceled.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
