/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-21 12:13:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005finterface_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<script >\r\n");
      out.write(" function openNewJSP2() {\r\n");
      out.write("    window.location.href = 'login.jsp';\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    // Prevent going forward or backward after one step\r\n");
      out.write("    var navigated = false;\r\n");
      out.write("    history.pushState(null, null, location.href);\r\n");
      out.write("    window.onpopstate = function () {\r\n");
      out.write("        if (!navigated) {\r\n");
      out.write("            navigated = true;\r\n");
      out.write("            history.go(1); // Go forward\r\n");
      out.write("            history.pushState(null, null, location.href); // Push another state to prevent further navigation\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" function openNewJSP1() {\r\n");
      out.write("	\r\n");
      out.write("	    window.location.href = 'registration.jsp'; // Redirect to newww.jsp\r\n");
      out.write("	}\r\n");
      out.write(" </script>\r\n");
      out.write("    \r\n");
      out.write("  <!-- Theme Made By www.w3schools.com -->\r\n");
      out.write("  <title>Bootstrap Theme Company Page</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  body, h1,h2,h3,h4,h5,h6 {font-family: \"Montserrat\", sans-serif}\r\n");
      out.write(".w3-row-padding img {margin-bottom: 12px}\r\n");
      out.write("/* Set the width of the sidebar to 120px */\r\n");
      out.write(".w3-sidebar {width: 120px;background: #222;}\r\n");
      out.write("/* Add a left margin to the \"page content\" that matches the width of the sidebar (120px) */\r\n");
      out.write("#main {margin-left: 120px}\r\n");
      out.write("/* Remove margins from \"page content\" on small screens */\r\n");
      out.write("@media only screen and (max-width: 600px) {#main {margin-left: 0}}\r\n");
      out.write("  body {\r\n");
      out.write("  \r\n");
      out.write("    font: 400 15px Lato, sans-serif;\r\n");
      out.write("    line-height: 1.8;\r\n");
      out.write("    color: #818181;\r\n");
      out.write("     font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("       \r\n");
      out.write("  }\r\n");
      out.write("  h2 {\r\n");
      out.write("  \r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  h4 {\r\n");
      out.write("    font-size: 19px;\r\n");
      out.write("    line-height: 1.375em;\r\n");
      out.write("    color: #303030;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }  \r\n");
      out.write("  .jumbotron {\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  background: url('images/2.jpg.jpg') no-repeat center center fixed;\r\n");
      out.write("    filter: brightness(0.9) saturate(100%) hue-rotate(360deg);\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 100px 25px;\r\n");
      out.write("    font-family: Montserrat, sans-serif;\r\n");
      out.write("  }\r\n");
      out.write("  .container-fluid {\r\n");
      out.write("    padding: 60px 50px;\r\n");
      out.write("  }\r\n");
      out.write(".main {\r\n");
      out.write("   \r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container {\r\n");
      out.write("       margin-right: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".homeBT1, .homeBT2 {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 30px 30px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    border: 1px solid #F0F8FF;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    font-family: Georgia, serif;\r\n");
      out.write("    transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".homeBT1 {\r\n");
      out.write("    background-color:rgb(199, 169, 243);\r\n");
      out.write("      text-decoration: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".homeBT2 {\r\n");
      out.write("    background-color:  rgb(0, 149, 199);\r\n");
      out.write("      text-decoration: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".homeBT1:hover, .homeBT2:hover {\r\n");
      out.write("    background-color: #fff; /* Change this to the desired hover background color */\r\n");
      out.write("    color: #000; /* Change this to the desired hover text color */\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".main-title{\r\n");
      out.write("margin-top: 150px;\r\n");
      out.write("margin-bottom: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".OUR-SERVICES-Main img{\r\n");
      out.write("margin-top: 300px;\r\n");
      out.write(" background-color: blue;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    padding: 1000px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    width: 10px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" a:link {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      \r\n");
      out.write("}\r\n");
      out.write("     .mymain1:hover {\r\n");
      out.write("      transform: scale(1.03);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(".about-section {\r\n");
      out.write("  padding: 50px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background-color: #474e5d;\r\n");
      out.write("  color: white;\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write(" text-decoration: none !important;\r\n");
      out.write("}\r\n");
      out.write(".pricing-table {\r\n");
      out.write("    width: 5%; /* Adjust this value as needed */\r\n");
      out.write("    float: left; /* Ensures the elements are displayed side by side */\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .image-container {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-container img {\r\n");
      out.write(" \r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%, -50%) scale(1);\r\n");
      out.write("    animation: scaleRotateAnimation 3s alternate infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes scaleRotateAnimation {\r\n");
      out.write("    0% {\r\n");
      out.write("        transform: translate(-50%, -50%) scale(1) rotate(0deg);\r\n");
      out.write("    }\r\n");
      out.write("    100% {\r\n");
      out.write("        transform: translate(-50%, -50%) scale(1.2) rotate(360deg);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"60\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("                           \r\n");
      out.write("      \r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#myPage\">EcoWash</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("       \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron text-center\">\r\n");
      out.write("      <div class=\"button-container\">\r\n");
      out.write("            <a class=\"homeBT1\"  target=\"_blank\"onclick=\"openNewJSP1()\" >SIGN UP</a>\r\n");
      out.write("            <a class=\"homeBT2\" target=\"_blank\"onclick=\"openNewJSP2()\">LOGIN</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"image-container\">\r\n");
      out.write("    <img src=\"images/wash1.png\" alt=\"Only Wash\" width=\"300\" height=\"300\">\r\n");
      out.write("</div>\r\n");
      out.write("        \r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"about-section\">\r\n");
      out.write("    \r\n");
      out.write("  <h1>About Us Page</h1>\r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("        <p >\r\n");
      out.write("Welcome to our Laundry Service System, where we are committed to being your dedicated partner in simplifying and enhancing your laundry care routine. At the heart of our mission lies a relentless pursuit of efficiency and convenience, driven by our desire to redefine the entire laundry experience for our valued customers.\r\n");
      out.write("\r\n");
      out.write("In today's fast-paced world, time is of the essence, and mundane tasks like laundry can often feel like a chore. That's why we've made it our goal to seamlessly integrate technology and convenience into every aspect of our service. From scheduling pickups to tracking the progress of your laundry, our intuitive platform puts the power in your hands, allowing you to manage your laundry needs with ease and flexibility.\r\n");
      out.write("        </p>\r\n");
      out.write("       \r\n");
      out.write("</div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("<div id=\"Service\" class=\"container-fluid text-center bg-grey\">\r\n");
      out.write("  <h2>At Your Service</h2><br>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row text-center slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <img src=\"images/wash1.jpg\" alt=\"Wash + Press\" width=\"430\" height=\"300\">\r\n");
      out.write("        <p><strong>Wash + Press</strong></p>\r\n");
      out.write("       <p>Ã¢ÂÂA wardrobe full of fresh, clean clothes which are neatly pressedÃ¢ÂÂ Sounds like an \r\n");
      out.write("       impossible dream? We are here to make it possible! Don't waste \r\n");
      out.write("       another beautiful Weekend for washing, drying and folding laundry. \r\n");
      out.write("       Let washapp to handle the dirty work while you spend your time enjoying life.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <img src=\"images/only_wash.jpg\" alt=\"Only Wash\" width=\"330\" height=\"200\">\r\n");
      out.write("        <p><strong>Only Wash</strong></p>\r\n");
      out.write("        <p>We bring you a bag, you fill it with clothes. We then send your dirty clothes for a quick spin,\r\n");
      out.write("         tumble dry and return them to you crisp clean. This service is charged per kilo, so donÃ¢ÂÂt hesitate to send us a truckload of work! \r\n");
      out.write("         But please remember, items that require extra care including toweling and bedding should be selected separately.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <img src=\"images/dray.jpg\" alt=\"Dry Clean\" width=\"230\" height=\"100\">\r\n");
      out.write("        <p><strong>Dry Clean</strong></p>\r\n");
      out.write("       <p> Delicate fabrics that canÃ¢ÂÂt withstand detergent? Tired of rushing around and re-arranging your schedule trying to make it in time to drop off or pic\r\n");
      out.write("       k up your dry cleaning? Wouldn't it be nice to have freshly pressed suits delivered rig\r\n");
      out.write("       ht to your door, right when you need them? With Washapp, now you can!</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div><br>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <div class=\"text-center\">\r\n");
      out.write("    <h2>EcoWash CORE BENEFITS</h2>\r\n");
      out.write("    <br>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4 col-xs-12\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <div class=\"panel panel-default text-center\">\r\n");
      out.write("       <div class=\"mymain1\">\r\n");
      out.write("        <div class=\"panel-heading\">\r\n");
      out.write("        <img src=\"images/c1.jpg\" alt=\"Wash + Press\" width=\"200\" height=\"200\">\r\n");
      out.write("          <h1>Customer Experience</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel-body\">\r\n");
      out.write("          <p><strong></strong> Everything about Bundle is centred on our clients and their success. That's precisely why we've built our portal to ensure all clients have visibility, transparency and ownership of their operations.</p>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>      \r\n");
      out.write("    </div>   \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("      \r\n");
      out.write("    <div class=\"col-sm-4 col-xs-12\">\r\n");
      out.write("      <div class=\"panel panel-default text-center\">\r\n");
      out.write("       <div class=\"mymain1\">\r\n");
      out.write("        <div class=\"panel-heading\">\r\n");
      out.write("          <img src=\"images/c2.jpg\" alt=\"Wash + Press\" width=\"200\" height=\"200\">\r\n");
      out.write("          <h1>Automate Processes</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel-body\">\r\n");
      out.write("          <p><strong>50</strong>Productivity is at the heart of any business's success and we understand this better than anyone. Our entire suite has been constructed with the objective of ensuring trust, efficiency and reliability.</p>\r\n");
      out.write("        \r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("      </div>      \r\n");
      out.write("    </div>       \r\n");
      out.write("    <div class=\"col-sm-4 col-xs-12\">\r\n");
      out.write("      <div class=\"panel panel-default text-center\">\r\n");
      out.write("       <div class=\"mymain1\">\r\n");
      out.write("        <div class=\"panel-heading\">\r\n");
      out.write("          <img src=\"images/c3.jpg\" alt=\"Wash + Press\" width=\"200\" height=\"200\">\r\n");
      out.write("          <h1>Increase Productivity</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel-body\">\r\n");
      out.write("          <p><strong></strong> Manual processes hinder operations and lead to inefficiency and errors - leaving your operation vulnerable. Our suite has the capacity and capability to completely modernise your various operations.</p>\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>      \r\n");
      out.write("    </div>    \r\n");
      out.write("\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("      <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("        <ul class=\"w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off\">\r\n");
      out.write("          <li class=\"w3-dark-grey w3-xlarge w3-padding-32\"></li>\r\n");
      out.write("          <li class=\"w3-padding-16\"><img src=\"images/homwach.png\" alt=\"Wash + Press\" width=\"400\" height=\"400\">\r\n");
      out.write("          <li class=\"w3-padding-16\"></li>\r\n");
      out.write("          <li class=\"w3-padding-16\">\r\n");
      out.write("            <h2>$ 10</h2>\r\n");
      out.write("            <span class=\"w3-opacity\"></span>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("            <a class=\"w3-button w3-white w3-padding-large w3-hover-black\" onclick=\"openNewJSP2()\">Order Add</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"w3-half\">\r\n");
      out.write("        <ul class=\"w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off\">\r\n");
      out.write("          <li class=\"w3-dark-grey w3-xlarge w3-padding-32\"></li>\r\n");
      out.write("     <li class=\"w3-padding-16\"><img src=\"images/only_wash.jpg\" alt=\"Wash + Press\" width=\"450\" height=\"400\">\r\n");
      out.write("    \r\n");
      out.write("          <li class=\"w3-padding-16\"></li>\r\n");
      out.write("          <li class=\"w3-padding-16\">\r\n");
      out.write("            <h2>$ 25</h2>\r\n");
      out.write("            <span class=\"w3-opacity\"></span>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("            <a class=\"w3-button w3-white w3-padding-large w3-hover-black\" onclick=\"openNewJSP2()\">Order Add</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
